# Generated by Django 2.1.8 on 2019-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('username', models.CharField(max_length=32)),
                ('age', models.CharField(blank=True, max_length=4, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img')),
                ('user_type', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
