# Generated by Django 2.1.8 on 2019-11-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_title', models.CharField(max_length=128)),
                ('g_introduction', models.CharField(max_length=128)),
                ('g_price', models.CharField(max_length=12)),
                ('g_original_price', models.CharField(max_length=12)),
                ('g_inventory', models.IntegerField()),
                ('g_photo', models.ImageField(upload_to='images')),
                ('g_hits', models.IntegerField(blank=True, null=True)),
                ('Whether_the_hot', models.CharField(default=0, max_length=4)),
                ('Whether_the_new', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=32)),
                ('r_introduction', models.CharField(max_length=128)),
                ('r_picture', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32)),
                ('c_price', models.CharField(max_length=12)),
                ('c_num', models.IntegerField()),
                ('c_photo', models.ImageField(upload_to='images')),
                ('c_price_sum', models.CharField(max_length=32)),
                ('c_add_time', models.DateTimeField()),
                ('c_inventory', models.IntegerField()),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Goods')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Retail')),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_classify', models.CharField(max_length=32)),
                ('t_picture', models.ImageField(upload_to='img')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Retail')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=18)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.CharField(blank=True, max_length=4, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img')),
                ('user_type', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Retail'),
        ),
        migrations.AddField(
            model_name='goods',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.ShopType'),
        ),
    ]
