# Generated by Django 2.1.8 on 2019-11-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_retail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_title', models.CharField(max_length=128)),
                ('g_introduction', models.CharField(max_length=128)),
                ('g_price', models.CharField(max_length=12)),
                ('g_original_price', models.CharField(max_length=12)),
                ('g_inventory', models.IntegerField()),
                ('g_hits', models.IntegerField(blank=True, null=True)),
                ('Whether_the_hot', models.CharField(default=0, max_length=4)),
                ('Whether_the_new', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_classify', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='retail',
            name='r_introduction',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='goods',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Retail'),
        ),
        migrations.AddField(
            model_name='goods',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.ShopType'),
        ),
    ]
