# Generated by Django 2.1.8 on 2019-11-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_auto_20191111_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='t_classify',
            field=models.CharField(max_length=32),
        ),
    ]
