# Generated by Django 2.1.8 on 2019-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_auto_20191111_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='g_photo',
            field=models.ImageField(default='buyer\\images', upload_to='images'),
            preserve_default=False,
        ),
    ]
