# Generated by Django 2.1.8 on 2019-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_goods_g_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptype',
            name='t_picture',
            field=models.ImageField(default='buyer/images/', upload_to='img'),
            preserve_default=False,
        ),
    ]
