# Generated by Django 2.1.8 on 2019-11-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_shoptype_t_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptype',
            name='r_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buyer.Retail'),
            preserve_default=False,
        ),
    ]
